# Generated by Django 6.0.3 on 2026-04-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
