# Generated by Django 6.0.3 on 2026-05-02 05:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_table_qr_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='menu_images'),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
