# Generated by Django 6.0.4 on 2026-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_table_qr_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
