# Generated by Django 6.0.3 on 2026-05-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuitem_image_alter_table_qr_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='table',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ordersession'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting Status'), ('PREPARING', 'In Kitchen'), ('SERVED', 'Served'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
